# Site wide configuration

title: Sphoorti Joglekar
locale: en_US
description: Computer Engineer | DIY Enthusiast | FOSS
logo: site-logo.png
search: true
url: http://sphoorti.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Sphoorti Joglekar
  avatar: bio-photo.jpg
  email: sphoorti.joglekar@gmail.com
  disqus-shortname:
  twitter: SphoortiJ
  facebook: #username
  github: sphoorti
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: sphoorti-joglekar/90/775/29
  instagram: sphoortij
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #Sphoorti Joglekar
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Projects
    url: /projects/
